repos:
  - repo: local
    hooks:
      - id: markdownlint
        name: markdownlint (autocorrect)
        entry: markdownlint-cli2 --fix
        language: system
        files: \.md$
      - id: shfmt
        name: shfmt
        entry: shfmt -w -i 2 -ci
        language: system
        files: ^scripts/.*\.sh$
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        files: ^scripts/.*\.sh$
